[versions]
cardiologist = "0.8.0"
clikt = "5.1.0"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
mosaic = "0.18.0"

[libraries]
cardiologist = { module = "io.github.kevincianfarini.cardiologist:cardiologist", version.ref = "cardiologist" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotlin-test-core = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mosaic = { module = "com.jakewharton.mosaic:mosaic-runtime", version.ref = "mosaic" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
